config/routes.rb
Rails.application.routes.draw do
  resources :trackers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tracker.rb
class Tracker < ApplicationRecord
	def self.search(topic, page)
	  if topic
	    where('name LIKE ?', "%#{topic}%").paginate(page: page, per_page: 30).order('id DESC')
	  else
	    paginate(page: page, per_page: 30).order('id DESC') 
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: [:show, :edit, :update, :destroy]
  
  # GET /trackers
  # GET /trackers.json
  def index
    @trackers = Tracker.search(params[:topic], params[:page])
    #Tracker.page(params[:page]).order('created_at DESC')

    #Tracker.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
    #Post.page(params[:page]).order('created_at DESC')

  end

  # GET /trackers/1
  # GET /trackers/1.json
  def show
  end

  # GET /trackers/new
  def new
    @tracker = Tracker.new
  end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers
  # POST /trackers.json
  def create
    @tracker = Tracker.new(tracker_params)

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to @tracker, notice: 'Tracker was successfully created.' }
        format.json { render :show, status: :created, location: @tracker }
      else
        format.html { render :new }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1
  # PATCH/PUT /trackers/1.json
  def update
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to @tracker, notice: 'Tracker was successfully updated.' }
        format.json { render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1
  # DELETE /trackers/1.json
  def destroy
    @tracker.destroy
    respond_to do |format|
      format.html { redirect_to trackers_url, notice: 'Tracker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tracker_params
      params.require(:tracker).permit(:client_id, :topic, :message,:created_at, :updated_at)
    end

    def set_page
      @page = params[:page] || 0
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gprs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trackers/_form.html.erb
<%= form_with(model: tracker, local: true) do |form| %>
  <% if tracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tracker.errors.count, "error") %> prohibited this tracker from being saved:</h2>

      <ul>
      <% tracker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.text_field :client_id %>
  </div>

  <div class="field">
    <%= form.label :topic %>
    <%= form.text_field :topic %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trackers/edit.html.erb
<h1>Editing Tracker</h1>

<%= render 'form', tracker: @tracker %>

<%= link_to 'Show', @tracker %> |
<%= link_to 'Back', trackers_path %>

app/views/trackers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trackers</h1>
<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Topic</th>
      <th>Message</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trackers.each do |tracker| %>
      <tr>
        <td><%= tracker.client_id %></td>
        <td><%= tracker.topic %></td>
        <td><%= tracker.message %></td>
        <td><%= tracker.created_at %></td>
        <td><%= tracker.updated_at %></td>
        <td><%= link_to 'Show', tracker %></td>
        <td><%= link_to 'Edit', edit_tracker_path(tracker) %></td>
        <td><%= link_to 'Destroy', tracker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @trackers %>


<%= link_to 'New Tracker', new_tracker_path %>

app/views/trackers/new.html.erb
<h1>New Tracker</h1>

<%= render 'form', tracker: @tracker %>

<%= link_to 'Back', trackers_path %>

app/views/trackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @tracker.client_id %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @tracker.topic %>
</p>

<p>
  <strong>Message:</strong>
  <%= @tracker.message %>
</p>

<%= link_to 'Edit', edit_tracker_path(@tracker) %> |
<%= link_to 'Back', trackers_path %>